package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	SalesOrder struct {
		SalesOrder                string      `json:"document_no"`
		Plant                     string      `json:"deliver_to"`
		OrderQuantity             string      `json:"quantity"`
		PickedQuantity            string      `json:"picked_quantity"`
		NetPriceAmount            string      `json:"price"`
	    Batch                     string      `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string      `json:"document_no"`
		Status               string      `json:"status"`
		DeliverTo            string      `json:"deliver_to"`
		Quantity             string      `json:"quantity"`
		CompletedQuantity    string      `json:"completed_quantity"`
	    PlannedStartDate     string      `json:"planned_start_date"`
	    PlannedValidatedDate string      `json:"planned_validated_date"`
	    ActualStartDate      string      `json:"actual_start_date"`
	    ActualValidatedDate  string      `json:"actual_validated_date"`
	    Batch                string      `json:"batch"`
		Work              struct {
			WorkNo                   string      `json:"work_no"`
			Quantity                 string      `json:"quantity"`
			CompletedQuantity        string      `json:"completed_quantity"`
			ErroredQuantity          string      `json:"errored_quantity"`
			Component                string      `json:"component"`
			PlannedComponentQuantity string      `json:"planned_component_quantity"`
			PlannedStartDate         string      `json:"planned_start_date"`
			PlannedStartTime         string      `json:"planned_start_time"`
			PlannedValidatedDate     string      `json:"planned_validated_date"`
			PlannedValidatedTime     string      `json:"planned_validated_time"`
			ActualStartDate          string      `json:"actual_start_date"`
			ActualStartTime          string      `json:"actual_start_time"`
			ActualValidatedDate      string      `json:"actual_validated_date"`
			ActualValidatedTime      string      `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema                         string `json:"api_schema"`
	Accepter                        []string `json:"accepter"`
	MaterialCode                      string `json:"material_code"`
	Supplier                          string `json:"plant/supplier"`
	Stock                             string `json:"stock"`
	SalesOrderType                    string `json:"document_type"`
	SONumber                          string `json:"document_no"`
	ScheduleLineDeliveryDate          string `json:"planned_date"`
	ValidatedDate                     string `json:"validated_date"`
    Deleted                           bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey  string `json:"connection_key"`
	Result         bool   `json:"result"`
	RedisKey       string `json:"redis_key"`
	Filepath       string `json:"filepath"`
	Characteristic struct {
		DeleteMc                      bool        `json:"DeleteMc"`
		UpdateMc                      bool        `json:"UpdateMc"`
		ToCharacteristicDescOc        bool        `json:"ToCharacteristicDescOc"`
		ToCharacteristicReferenceOc   bool        `json:"ToCharacteristicReferenceOc"`
		ToCharacteristicRestrictionOc bool        `json:"ToCharacteristicRestrictionOc"`
		ToCharacteristicValueOc       bool        `json:"ToCharacteristicValueOc"`
		CharcInternalID               string      `json:"CharcInternalID"`
		Characteristic                string      `json:"Characteristic"`
		CharcStatus                   string      `json:"CharcStatus"`
		CharcStatusName               string      `json:"CharcStatusName"`
		CharcDataType                 string      `json:"CharcDataType"`
		CharcLength                   int         `json:"CharcLength"`
		CharcDecimals                 int         `json:"CharcDecimals"`
		CharcTemplate                 string      `json:"CharcTemplate"`
		ValueIsCaseSensitive          bool        `json:"ValueIsCaseSensitive"`
		CharcGroup                    string      `json:"CharcGroup"`
		CharcGroupName                string      `json:"CharcGroupName"`
		EntryIsRequired               bool        `json:"EntryIsRequired"`
		MultipleValuesAreAllowed      bool        `json:"MultipleValuesAreAllowed"`
		CharcValueUnit                string      `json:"CharcValueUnit"`
		Currency                      string      `json:"Currency"`
		CharcExponentValue            int         `json:"CharcExponentValue"`
		ValueIntervalIsAllowed        bool        `json:"ValueIntervalIsAllowed"`
		AdditionalValueIsAllowed      bool        `json:"AdditionalValueIsAllowed"`
		NegativeValueIsAllowed        bool        `json:"NegativeValueIsAllowed"`
		ValidityStartDate             string      `json:"ValidityStartDate"`
		ValidityEndDate               string      `json:"ValidityEndDate"`
		ChangeNumber                  string      `json:"ChangeNumber"`
		DocumentType                  string      `json:"DocumentType"`
		DocNumber                     string      `json:"DocNumber"`
		DocumentVersion               string      `json:"DocumentVersion"`
		DocumentPart                  string      `json:"DocumentPart"`
		CharcMaintAuthGrp             string      `json:"CharcMaintAuthGrp"`
		CharcIsReadOnly               bool        `json:"CharcIsReadOnly"`
		CharcIsHidden                 bool        `json:"CharcIsHidden"`
		CharcIsRestrictable           bool        `json:"CharcIsRestrictable"`
		CharcExponentFormat           string      `json:"CharcExponentFormat"`
		CharcEntryIsNotFormatCtrld    bool        `json:"CharcEntryIsNotFormatCtrld"`
		CharcTemplateIsDisplayed      bool        `json:"CharcTemplateIsDisplayed"`
		CreationDate                  string      `json:"CreationDate"`
		LastChangeDate                string      `json:"LastChangeDate"`
		CharcLastChangedDateTime      string      `json:"CharcLastChangedDateTime"`
		KeyDate                       string      `json:"KeyDate"`
		Value                         struct {
			DeleteMc                  bool        `json:"DeleteMc"`
			UpdateMc                  bool        `json:"UpdateMc"`
			ToCharcValueDescOc        bool        `json:"ToCharcValueDescOc"`
			CharcValuePositionNumber  string      `json:"CharcValuePositionNumber"`
			CharcValueDependency      string      `json:"CharcValueDependency"`
			CharcValue                string      `json:"CharcValue"`
			CharcFromNumericValue     string      `json:"CharcFromNumericValue"`
			CharcToNumericValue       string      `json:"CharcToNumericValue"`
			IsDefaultValue            bool        `json:"IsDefaultValue"`
			CharcFromNumericValueUnit string      `json:"CharcFromNumericValueUnit"`
			CharcToNumericValueUnit   string      `json:"CharcToNumericValueUnit"`
			LongTextID                string      `json:"LongTextID"`
			ChangeNumber              string      `json:"ChangeNumber"`
			DocumentType              string      `json:"DocumentType"`
			DocNumber                 string      `json:"DocNumber"`
			DocumentPart              string      `json:"DocumentPart"`
			DocumentVersion           string      `json:"DocumentVersion"`
			ValidityStartDate         string      `json:"ValidityStartDate"`
			ValidityEndDate           string      `json:"ValidityEndDate"`
			KeyDate                   string      `json:"KeyDate"`
			CharcLastChangedDateTime  string      `json:"CharcLastChangedDateTime"`
			ValueDescription          struct {
				DeleteMc                 bool        `json:"DeleteMc"`
				UpdateMc                 bool        `json:"UpdateMc"`
				Language                 string      `json:"Language"`
				CharcValueDescription    string      `json:"CharcValueDescription"`
				ChangeNumber             string      `json:"ChangeNumber"`
				ValidityStartDate        string      `json:"ValidityStartDate"`
				ValidityEndDate          string      `json:"ValidityEndDate"`
				KeyDate                  string      `json:"KeyDate"`
				CharcLastChangedDateTime string      `json:"CharcLastChangedDateTime"`
			} `json:"ValueDescription"`
		} `json:"Value"`
		CharcDescription struct {
			DeleteMc                 bool        `json:"DeleteMc"`
			UpdateMc                 bool        `json:"UpdateMc"`
			CharcInternalID          string      `json:"CharcInternalID"`
			Language                 string      `json:"Language"`
			CharcDescription         string      `json:"CharcDescription"`
			ChangeNumber             string      `json:"ChangeNumber"`
			ValidityStartDate        string      `json:"ValidityStartDate"`
			ValidityEndDate          string      `json:"ValidityEndDate"`
			KeyDate                  string      `json:"KeyDate"`
			CharcLastChangedDateTime string      `json:"CharcLastChangedDateTime"`
		} `json:"CharcDescription"`
	} `json:"Characteristic"`
	APISchema          string   `json:"api_schema"`
	Accepter           []string `json:"accepter"`
	CharacteristicCode string   `json:"characteristic_code"`
	Deleted            bool     `json:"deleted"`
}
